name: Build
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: git.madways.org
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build
        run: docker build . -t ${{ secrets.IMAGE }}:latest
      - name: Push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push ${{ secrets.IMAGE }}:latest
